import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faArrowLeft,
  faArrowUpFromBracket,
  faCalendarDays,
  faChartColumn,
  faClipboardCheck,
  faCopy,
  faDatabase,
  faDumbbell,
  faEye,
  faFloppyDisk,
  faFutbol,
  faGauge,
  faKitMedical,
  faMagnifyingGlass,
  faPen,
  faPersonRunning,
  faPlus,
  faQrcode,
  faRightFromBracket,
  faTrash,
  faTriangleExclamation,
  faTrophy,
  faUser,
  faUsers,
  faVideo,
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
  dashboard:   <FontAwesomeIcon icon={faGauge} />,
  user:        <FontAwesomeIcon icon={faUser} />,
  users:       <FontAwesomeIcon icon={faUsers} />,
  trainings:   <FontAwesomeIcon icon={faDumbbell} />,
  attendances: <FontAwesomeIcon icon={faClipboardCheck} />,
  calendar:    <FontAwesomeIcon icon={faCalendarDays} />,
  media:       <FontAwesomeIcon icon={faVideo} />,
  scan:        <FontAwesomeIcon icon={faQrcode} />,
  upload:      <FontAwesomeIcon icon={faArrowUpFromBracket} />,
  plus:        <FontAwesomeIcon icon={faPlus} />,
  edit:        <FontAwesomeIcon icon={faPen} />,
  delete:      <FontAwesomeIcon icon={faTrash} />,
  search:      <FontAwesomeIcon icon={faMagnifyingGlass} />,
  back:        <FontAwesomeIcon icon={faArrowLeft} />,
  save:        <FontAwesomeIcon icon={faFloppyDisk} />,
  view:        <FontAwesomeIcon icon={faEye} />,
  copy:        <FontAwesomeIcon icon={faCopy} />,
  warning:     <FontAwesomeIcon icon={faTriangleExclamation} />,
  logout:      <FontAwesomeIcon icon={faRightFromBracket} />,
  progression: <FontAwesomeIcon icon={faDatabase} />,
  development: <FontAwesomeIcon icon={faChartColumn} />,
  microcycles: <FontAwesomeIcon icon={faFutbol} />,
  mesocycles:  <FontAwesomeIcon icon={faPersonRunning} />,
  macrocycles: <FontAwesomeIcon icon={faTrophy} />,
  injuries:    <FontAwesomeIcon icon={faKitMedical} />,
}
